class Aircraft:
    """
    Represents an aircraft detected by dump1090.

    The `data` object is the JSON object that represents an aircraft in the
    `aircraft.json` file generated by dump1090.
    """

    def __init__(self, data):
        self.dump1090_data = data
        self.aircraft_data = {}
        self.operator_data = {}

    def update_dump1090_data(self, data):
        data = { k: v for k,v in data.items() if v is not None }
        self.dump1090_data = self.dump1090_data | data

    def has_aircraft_data(self) -> bool:
        return bool(self.aircraft_data)

    def update_aircraft_data(self, data):
        self.aircraft_data = data

    def has_operator_data(self) -> bool:
        return bool(self.operator_data)

    def update_operator_data(self, data):
        self.operator_data = data

    def icao_hex(self) -> str:
        return self.dump1090_data.get("hex").upper()

    def flight(self):
        return self.dump1090_data.get("flight", None)

    def altitude(self):
        return self.dump1090_data.get("alt_baro", None)

    def squawk(self):
        return self.dump1090_data.get("squawk", None)

    def registration(self):
        return self.aircraft_data.get("registration", None)

    def aircraft_type(self):
        return self.aircraft_data.get("type", None)

    def name(self):
        return self.aircraft_data.get("name", None)

    def operator_prefix(self):
        return self.operator_data.get("prefix", None)

    def operator_name(self):
        return self.operator_data.get("name", None)

    def operator_country(self):
        return self.operator_data.get("country", None)
