import json

class Aircraft:
    """
    Represents an aircraft detected by dump1090.

    The `data` object is the JSON object that represents an aircraft in the
    `aircraft.json` file generated by dump1090.
    """

    def __init__(self, data):
        self.data = data

    def icao_hex(self):
        return self.data.get("hex", None)

    def flight(self):
        return self.data.get("flight", None)

    def altitude(self):
        return self.data.get("alt_baro", None)

    def squawk(self):
        return self.data.get("squawk", None)

with open("/tmp/aircraft.json", "r") as f:
    data = json.loads(f.read())
    aircrafts = []

    for aircraft_data in data["aircraft"]:
        aircraft = Aircraft(aircraft_data)
        print("------------------------------")
        print("ICAO: ", aircraft.icao_hex())
        print("FLIGHT: ", aircraft.flight())
        print("ALTITUDE: ", aircraft.altitude())
        print("SQUAWK: ", aircraft.squawk())

        aircrafts.append(aircraft)
